# Application name
spring.application.name=lextiming

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lextimingdb
spring.datasource.username=lextiming_user
spring.datasource.password=Viva_la_libertad@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.lextiming=DEBUG

# Server
server.port=8080
